version: 2.1
 
jobs:
  say-hello:
    docker:
      - image: 'continuumio/miniconda3:4.7.10'
    steps:
      - checkout
      - run:
          name: Set up conda environment
          command: |
            #exit 1
            conda create -n tcdf python=3.6
            conda init
            . ~/.bashrc
            source activate tcdf
            conda install pytorch==0.4.1
            pip install -r requirements.txt

            python runTCDF.py --help
            python runTCDF.py --data data/demo_dataset.csv

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
