version: 2.1
 
jobs:
  say-hello:
    docker:
      - image: 'continuumio/miniconda3:4.7.10'
    steps:
      - checkout
      - run:
          name: Set up conda environment
          command: |
            exit 1
            #conda create -n tcdf python=3.6
            #conda activate tcdf
            #conda install pytorch==0.4.1

workflows:
  say-hello-workflow:
    jobs:
      - say-hello
