name: Build and test TCDF

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.7
      uses: actions/setup-python@v3
      with:
        python-version: '3.7'
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install Pytorch 0.4.1
      run: conda install pytorch==0.4.1
    - name: Install deps
      run: pip install -r requirements.txt
    - name: do smoke test
      run: python runTCDF.py --help
    - name: run demo data
      run: python runTCDF.py --data data/demo_dataset.csv
